"""
Django settings for Securevaultapi project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import os
import dj_database_url
from base64 import b64decode,b64encode
env=environ.Env()
environ.Env.read_env()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings.py

# BASE_URL and DEBUG are defined below near SECRET_KEY

BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent
MASTER_KEY=env('MASTER_KEY')
if not MASTER_KEY:
    raise ValueError("MASTER_KEY environment variable is not set")
MASTER_KEY=b64decode(MASTER_KEY)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
ENCRYPTED_FILES_DIR=os.path.join(MEDIA_ROOT,'encrypted')
os.makedirs(ENCRYPTED_FILES_DIR,exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#g!0w=x(yw8kdnxl9qd1%&rjtn7j(l3qapg(%6*4#=dawcp_^3"

# SECURITY WARNING: don't run with debug turned on in production!
# We define DEBUG here and let BASE_URL be derived from it.
DEBUG = env.bool("DEBUG", default=True) # Default to True for local dev unless overridden

if DEBUG:
    BASE_URL = env("BASE_URL", default="http://192.168.1.69:8000")
else:
    BASE_URL = env("BASE_URL", default="https://securevault-h1nz.onrender.com")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
# jjmc utbc zsmx dxew
# Valid examples your API should accept:
allowed_ips = [
    "192.168.1.10",        # single IPv4
    "10.0.0.0/24",         # IPv4 CIDR range
    "2001:db8::1",         # single IPv6
    "2001:db8::/32"        # IPv6 CIDR range
]

# Application definition

# settings.py

# Email backend for sending emails
EMAIL_BACKEND = 'api.backends.email_backend.EmailBackend'

# Gmail SMTP server configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Your Gmail credentials (use App Password, not normal password for security)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# DEFAULT_FROM_EMAIL can be a Gmail address for SMTP or a verified Resend sender.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
# EMAIL_PROVIDER: 'smtp' for local dev (Gmail SMTP), 'resend' for production (requires verified domain)
EMAIL_PROVIDER = env('EMAIL_PROVIDER', default='smtp').lower()
RESEND_API_KEY = env('RESEND_API_KEY', default='')
RESEND_API_URL = env('RESEND_API_URL', default='https://api.resend.com/emails')

# Async email via Celery. Works locally with Redis + Gmail SMTP.
# In production, pair with EMAIL_PROVIDER=resend once you have a verified domain.
SEND_EMAILS_ASYNC = env.bool('SEND_EMAILS_ASYNC', default=True)

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'api',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "corsheaders",
    "django_redis",
    "channels",
    
    
    
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'api.middleware.location_tracking.SecurityMiddleware'
]

ROOT_URLCONF = "Securevaultapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Securevaultapi.wsgi.application"
ASGI_APPLICATION = "Securevaultapi.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# Database configuration
DATABASE_URL = env("DATABASE_URL", default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env("DB_NAME"),
            'USER': env("DB_USER"),
            'PASSWORD': env("DB_PASSWORD"),
            'HOST': env("DB_HOST"),
            'PORT': env("DB_PORT")
        }
    }
# postgresql://securevault_k7ob_user:S6yByHcUTTaf41nJYCizVMYErpZMa2ai@dpg-d0ivglumcj7s7393hhvg-a.oregon-postgres.render.com/securevault_k7ob




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "api.MyUser"
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.BlacklistCheckJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'login': '5/minute',       
        'otp': '3/minute',         
        'burst': '60/minute',     
        'shared_resource': '60/minute', 
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
# Security headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
_REDIS_URL = env("REDIS_URL", default="redis://127.0.0.1:6379")
if _REDIS_URL.startswith('rediss://') and 'ssl_cert_reqs' not in _REDIS_URL:
    # Append ssl_cert_reqs=none for Upstash/Celery compatibility
    sep = '&' if '?' in _REDIS_URL else '?'
    REDIS_URL = f"{_REDIS_URL}{sep}ssl_cert_reqs=none"
else:
    REDIS_URL = _REDIS_URL


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL if REDIS_URL.startswith('rediss') else f"{REDIS_URL}/1",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'ssl_cert_reqs': 'none'} if REDIS_URL.startswith('rediss') else {}
        }
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}


CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8000",
    "http://127.0.0.1:9000",
    


]
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
# Celery 5.x+ specific SSL settings
CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': 'none'} if REDIS_URL.startswith('rediss') else False
CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': 'none'} if REDIS_URL.startswith('rediss') else False
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'

# Session Security
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF Protection
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://securevault-h1nz.onrender.com",
]

# Security Notification Settings
SECURITY_TEAM_EMAILS = ['pankajpandey.p18@gmail.com']
SECURITY_ALERT_EMAIL_COOLDOWN = 900  # 15 minutes in seconds

# Threat Detection
THREAT_DETECTION = {
    'AUTO_BLOCK_THRESHOLD': 75,  # Risk score threshold for auto-block
    'MAX_LOGIN_ATTEMPTS': 5,
    'LOGIN_ATTEMPT_WINDOW': 15,  # minutes
}

# File Upload Restrictions
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# File Transfer Settings
# 1 GB of file transfer
MAX_FILE_SIZE=1024*1024*1024 
# data is divided into chunks and that chunk is divided into 16KB
CHUNK_SIZE=16*1024
