# Generated by Django 5.2.1 on 2026-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sharedfileresource_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ed25519_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='rsa_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
