# Generated by Django 5.2.1 on 2026-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myuser_ed25519_public_key_myuser_rsa_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login attempt'), ('new_device', 'New device login'), ('new_location', 'New location'), ('location_change', 'Location change'), ('file_access', 'File access'), ('image_access', 'Image access'), ('password_change', 'Password change'), ('unusual_time_access', 'Unusual time access'), ('unusual_time', 'Unusual time access'), ('rapid_location_change', 'Rapid location change'), ('impossible_travel', 'Impossible travel'), ('multiple_device_access', 'Multiple device access'), ('multiple_failed_login', 'Multiple failed logins'), ('possible_session_hijack', 'Possible session hijack'), ('bulk_file_access', 'Bulk file access'), ('unusual_file_access', 'Unusual file access'), ('tampering_detected', 'Data tampering detected')], max_length=30),
        ),
    ]
