# Generated by Django 5.2.1 on 2026-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_suspiciousactivitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
