from django.urls import path
from api.views import (
    UserLoginView, 
    UserRegistrationView, 
    VerifyOtpView,
    ForgotPasswordView,
    ResetPasswordView,
    ResetOtpVerifyView,
    ResendOtpView,
    PasswordResetResendOTPView,
    UploadFileView,
    DownloadFileView,
    ListFilesView,
    AccessLogView,
    UploadImageView,
    DownloadImageView,
    ListImageView,
    ImageAccessLogView,
    ImageView,FileView,CreateShareLinkView,
    SharedResourceView,
    DeleteFile,
    DeleteImagesView,
    DeviceVerificationView,
    RoomListCreateView,
    RoomDetailView,
    RoomJoinView,
    RoomPeersView,
    FileTransferListCreateView,
    FileTransferDetailView,
    FileTransferCompleteView,
    FileTransferUpdateChunkView,
    LogoutView,
    ChangePasswordView,
    UpdateProfileView,
    GetUserProfile,RequestPasswordChangeOTPView,
    DashboardView,
    PublicKeyExchangeView,
) 

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="Login"),
    path("signup/", UserRegistrationView.as_view(), name="Registration"),
    path("verify-otp/", VerifyOtpView.as_view(), name="VerifyOtp"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="ForgotPassword"),
    path("reset-password/", ResetPasswordView.as_view(), name="ResetPassword"),
    path("reset-verify-otp/", ResetOtpVerifyView.as_view(), name="ResetPassword"),
    path("register-resend-otp/",ResendOtpView.as_view(),name="resendotp"),
    path("forgot-resend-otp/",PasswordResetResendOTPView.as_view(),name="forgotresendotp"),
    path('upload/',UploadFileView.as_view(),name="upload_file"),
    path('files/',ListFilesView.as_view(),name="files_list"),
    path('download/<int:file_id>',DownloadFileView.as_view(),name="download_file"),
    path('log/<int:file_id>',AccessLogView.as_view(),name="file_access_log"),
    path('UploadImage/',UploadImageView.as_view(),name="Upload_Image"),
    path('Listimages/',ListImageView.as_view(),name='Image Upload'),
    path('DownloadImage/<int:image_id>',DownloadImageView.as_view(),name="downloadimage"),
    path("imagelog/<int:image_id>",ImageAccessLogView.as_view(),name="Imagelog"),
    path("imageview/<int:image_id>",ImageView.as_view(),name="imageview"),
    path("fileview/<int:file_id>",FileView.as_view(),name="Fileview"),
    path("link/",CreateShareLinkView.as_view(),name="shareable link"),
    path("sharedresource/<uuid:share_id>",SharedResourceView.as_view(),name="Shared Resource"),
    path("deleteFile/<int:file_id>",DeleteFile.as_view(),name="delete File"),
    path("deleteImage/<int:image_id>",DeleteImagesView.as_view(),name="Delete Image"),
    path("verify-device/<uuid:token>/", DeviceVerificationView.as_view(), name="verify_device"),
    path("roomListCreateView/",RoomListCreateView.as_view(),name="RoomListCreateView"),
    path("roomDetailView/",RoomDetailView.as_view(),name="RoomDetailView"),
    path("roomJoinView/",RoomJoinView.as_view(),name="RoomJoinView"),
    path("roomPeersView/<uuid:pk>/",RoomPeersView.as_view(),name="RoomPeersView"),
    path("fileTransferListCreateView/",FileTransferListCreateView.as_view(),name="FileTransferListCreateView"),
    path("fileTransferDetailView/",FileTransferDetailView.as_view(),name="FileTransferDetailView"),
    path("fileTransferCompleteView/",FileTransferCompleteView.as_view(),name="FileTransferCompleteView"),
    path("fileTransferUpdateChunkView/",FileTransferUpdateChunkView.as_view(),name="FileTransferUpdateChunkView"),
    path("logout/",LogoutView.as_view(),name="Logout"),
    path("changepassword/",ChangePasswordView.as_view(),name="ChangePassword"),
    path("updateprofile/",UpdateProfileView.as_view(),name="UpdateProfile"),
    path("getUserProfile/",GetUserProfile.as_view(),name="UserProfile"),
    path('password/change/request-otp/', RequestPasswordChangeOTPView.as_view()),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # E2EE public key exchange
    path('exchange-keys/', PublicKeyExchangeView.as_view(), name='exchange_keys'),
]